language: python
python:
  - "2.7"
  - "3.5"
# command to install dependencies
install: "pip install -r solver/requirements.txt"
# command to run tests
script: nosetests --with-coverage --cover-erase --cover-package=simplex_networks,hpa_utilities --nocapture --verbosity 2 --no-byte-compile --process-timeout=3

