language: python
python:
  - "2.7"
  - "3.5"
install:
  - pip install -r solver/requirements.txt
  - pip install coveralls  

script: nosetests --with-coverage --cover-erase --cover-package=simplex_networks,hpa_utilities --nocapture --verbosity 2 --no-byte-compile --process-timeout=3

after_success:
  coveralls
